### ISSUE TITLE
指定模板文件作为snippet失败

### ISSUE THREAD

**Issue by VitaminC1989** [ATQQ/ShareSnippet#5]
### 环境：
1. Win10 
2. vscode
        版本: 1.53.2 (system setup)
        提交: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
        日期: 2021-02-11T11:48:04.245Z
        Electron: 11.2.1
        Chrome: 87.0.4280.141
        Node.js: 12.18.3
        V8: 8.7.220.31-electron.0
        OS: Windows_NT x64 10.0.18363

### 操作如图所示 未出现snippet提示
![QQ截图20210317164645](https://user-images.githubusercontent.com/35803403/111439567-77a6aa00-8740-11eb-812f-d4f0eddae058.png)

**Comment by VitaminC1989** [comment]
问题解决 写代码贼舒服😆

**Comment by ATQQ** [comment]
谢谢反馈O(∩_∩)O~~
