### ISSUE TITLE
refresh不生效

### ISSUE THREAD

**Issue by colorsweb** [ATQQ/ShareSnippet#6]
建了一个code-snippets文件，初始化是可以加载指令的，改了prefix并执行refresh新的指令不生效。reload window是可以的

**Comment by ATQQ** [comment]
可以说一下是哪个操作系统吗

**Comment by colorsweb** [comment]
mac catalina 10.15.6
node 14.15.0
vscode 1.55.2

**Comment by ATQQ** [comment]
> mac catalina 10.15.6
> node 14.15.0
> vscode 1.55.2

方便加个WX/QQ  2604395430 帮忙Debug一下吗 我这里没mac catalina 10.15.6 :sweat_smile: :

**Comment by ATQQ** [comment]
你刷新后右下角  有这个消息提示吗
![image](https://user-images.githubusercontent.com/42485491/116341388-6a86db80-a813-11eb-8305-5d398a6fd444.png)

**Comment by ATQQ** [comment]
发了个新版本 1.0.2
指令改成了 SP Refresh

![image](https://user-images.githubusercontent.com/42485491/116346982-e8e87b00-a81d-11eb-84f5-f6da34e62dfe.png)

**Comment by colorsweb** [comment]
刚看到，之前确实没有，新发的版本可以了！感谢大佬😀

**Comment by ATQQ** [comment]
不客气,感谢反馈
